'Pimiento Verde', 'Eschalote', 'Tomate', 'Lima', 'Mezcla de especias', 'Porotos negros', 'Guacamole', 'Crema agria', 'Tortillas de harina', 'Mezcla de Quesos', 'Queso Tybo';
'Arroz Jazmín', 'Eschalote', 'Glaseado de soja dulce', 'Salsa dulce de chile tailandés', 'Salsa Ponzu', 'Vinagre de arroz', 'Carne de cerdo molida', 'Polvo de ajo', 'Mezcla de col morada y zanahoria', 'Cebollas Fritas Crujientes', 'Arroz de Coliflor';
'Solomillo', 'Vinagre balsámico', 'Salsa de soja', 'Patatas Yukón Doradas', 'Romero', 'Cebolla amarilla', 'Repollo rojo rallado', 'Semillas de mostaza', 'Vinagre de vino blanco', 'Mermelada de arándano';
'Garbanzos', 'Mezcla Tempura', 'Cebolla morada', 'Polvo de curry', 'Eschalote', 'Arroz basmati', 'Yogur', 'Crema agria', 'Limón', 'Ajo', 'Pasas doradas', 'Espinaca', 'Anacardos', 'Concentrado de caldo de verduras';
'Ajo', 'Eschalot', 'Ají picante', 'Tomates ', 'Uva', 'Limón', 'Camarone', 'Pasta Tagliatelle', 'Crema agria';
'Garbanzos', 'Batata', 'Comino', 'Polvo de curry', 'Cebolla amarilla', 'Cilantro', 'Limón', 'Ajo', 'Jengibre', 'Lechuga Bebé', 'Guisantes', 'Mermelada de Pimientos Rojos';
'Cebolla amarilla', 'Jalapeño', 'Carne molida', 'Mezcla de Especias Mexicanas', 'Mezcla de especias del suroeste', 'Pasta de tomate', 'Tomates', 'Porotos negros', 'Concentrado de caldo de res', 'Crema agria', 'Salsa picante', 'Queso Tybo';
'Tomate', 'Cilantro', 'Lima', 'Pimiento Verde Largo', 'Cebolla amarilla', 'Crema agria', 'Salsa picante', 'Carne molida', 'Mezcla de especias del suroeste', 'chile en polvo', 'Concentrado de caldo de res', 'Tortillas de harina', 'Mezcla de Quesos Mexicanos';
'Jengibre', 'Ajo', 'Eschalote', 'Lima', 'Arroz Jazmín', 'Arvejas', 'Aceite de sésamo', 'Semillas de sésamo', 'Tiras de pollo', 'Salsa de soja', 'Vinagre de vino blanco', 'Maicena';
'Ajo', 'Cebolla morada', 'Garbanzos', 'Perejil', 'Arroz Basmati', 'Chile en polvo', 'Polvo de curry', 'Leche de coco', 'Tomates', 'Concentrado de caldo de verduras', 'Pitas de Trigo Integral';
'Ajo', 'Zucchini', 'Cebolla amarilla', 'Cuscús israelí', 'Salmón', 'Especias toscanas', 'Concentrado de Caldo de Pollo', 'Mermelada de Pimiento Rojo', 'Queso crema', 'Crema agria';
'Zuchinni', 'Champiñones', 'Eschalote', 'Zanahorias', 'Jengibre', 'Ajo', 'Arroz Jazmín', 'Vinagre de vino blanco', 'Aceite de sésamo', 'Sriracha', 'Salsa de soja', 'Carne molida';
'Champiñones Cremini', 'Cebolla amarilla', 'Pimiento Verde Largo', 'Papas', 'Aceite en spray', 'Mayonesa', 'Mostaza de Dijon', 'Media baguette', 'Especias para bistec atrevidas y sabrosas', 'Concentrado de caldo de champiñones', 'Queso mozzarella', 'Brócoli';
'Papas', 'Cebolla amarilla', 'Limón', 'bollos de patata', 'condimento para freír', 'Mayonesa', 'Mostaza de Dijon', 'Chuletas de Cerdo', 'Sal de apio', 'Tomillo seco', 'Harina', 'Concentrado de Caldo de Pollo';
'Coliflor', 'Ajo', 'Pasta Tex-Mex', 'Arroz Jazmín', 'Pimiento Verde Largo', 'Cebolla amarilla', 'Lima', 'Cilantro', 'Ananás', 'Mezcla de especias para fajitas', 'Guacamole';
'Cebolla amarilla', 'Pimiento Verde Largo', 'Tomate', 'Floretes de coliflor', 'Mezcla de especias del suroeste', 'Pasta de tomate', 'Frijoles negros', 'Pasta Tex-Mex', 'Concentrado de caldo de verduras', 'Cilantro', 'Chips de tortilla de maíz azul';
'Champiñones', 'Arvejas', 'Zanahorias', 'Fideos Udon', 'Jengibre', 'Ajo', 'Concentrado de caldo de verduras', 'Eschalote', 'Salsa Hoisin', 'Salsa de soja', 'Aceite de sésamo';
'Arroz Basmati', 'Garbanzos', 'Tomates de uva', 'Cebolla morada', 'Limón', 'Concentrado de caldo de verduras', 'Mezcla de especias turcas', 'Pistachos', 'Hummus', 'Ajo', 'Perejil', 'Ciboullette', 'Pasas doradas';
'Tofu', 'Cebolla amarilla', 'Zanahorias', 'Eschalot', 'Arroz Jazmín', 'Fo concentrado', 'Harina', 'Maicena', 'Guisantes', 'Aceite de sésamo', 'Soy Sauce', 'Salsa Katsu', 'Salsa hoisin', 'Salsa dulce de chile tailandés';
'Arroz Jazmín', 'Cebolla morada', 'Lima', 'Chile poblano', 'Tomate Roma', 'Cilantro', 'Proteína de origen vegetal molida', 'Mezcla de especias del suroeste', 'Pasta Tex-Mex', 'Crema agria';
'Batata', 'Mezcla de especias del suroeste', 'Cebolla morada', 'Pimiento Verde Largo', 'Tomate Perita', 'Lima', 'Cilantro', 'Jalapeño', 'Crmea agria', 'Tortillas de harina', 'Queso pimienta';
'Pimiento verde', 'Cebolla amarilla', 'Tomate Roma', 'Proteína de origen vegetal molida', 'Especias picantes toscanas', 'Pasta de tomate', 'Concentrado de caldo de verduras', 'Cuscús israelí', 'Queso mozzarella';
'Arroz Jamaní', 'Zanahoria', 'pepino persa', 'Jengibre', 'Ajo', 'cebolletas', 'Cilantro', 'Proteína de origen vegetal molida', 'vinagre de vino de arroz', 'Salsa dulce de chile tailandés', 'Glaseado de soja dulce', 'Maní';
'Proteína de origen vegetal molida', 'Pimiento morrón', 'Pasta Rigatoni', 'Pasta de tomate', 'Queso crema', 'Queso parmesano', 'Condimento italiano', 'Ciboullette';
'Arroz basmati', 'Cilantro', 'Ajo', 'Pimiento morrón', 'Cebolla roja', 'Cebolla de verdeo', 'Naranja', 'Lima', 'Orégano', 'Carré de Cerdo', 'Concentrado de Caldo de Pollo', 'Mermelada de damazco', 'Porotos negros';
'Papines', 'Eschalot', 'Arvejas verdes', 'Estragón', 'Tomates', 'Vinagre de vino blanco', 'Mostaza de Dijon', 'Crema agria', 'Bistec corte Rib-eye';
'Zanahorias', 'Ajo', 'Perejil', 'Papa roja', 'Pechugas de pollo', 'Tomillo', 'Pollo Demi-Glace', 'Leche', 'Queso parmesano';
'Papas Doradas', 'Zucchini', 'Queso parmesano', 'Pechugas de pollo', 'Arvejas', 'Leche', 'Limón';
'Cebolla amarilla', 'Romero', 'Patatas Yukón Doradas', 'Repollo rojo rallado', 'Semillas de mostaza', 'Vinagre de vino blanco', 'Solomillo', 'Vinagre balsámico', 'Salsa de Soja', 'Mermelada de arándano';
'Cebolla amarilla', 'Pimiento verde', 'Ajo', 'Jalapeño', 'Porotos negros', 'Maíz', 'Tortilla Chips', 'Mezcla de Especias Mexicanas', 'Tomates aplastados', 'Concentrado de caldo de verduras', 'Palta', 'Queso cheddar';
'Batata', 'Romero', 'Ajo', 'Tomates de uva', 'Bistec ranchero', 'Avejas verdes', 'Vinagre balsámico', 'Concentrado de caldo de res';
'Zanahorias', 'Ajo', 'Eschalot', 'Perejil', 'Cuscús israelí', 'Concentrado de caldo de res', 'Chuletas De Cerdo', 'Condimento italiano', 'Pasta de tomate', 'Crema agria';
'Flores de brócoli', 'Jengibre', 'cebolletas', 'Mayonesa', 'Salsa dulce de chile tailandés', 'Pavo molido', 'Salsa Ponzu', 'Fo concentrado', 'Migas de pan Panko', 'Repollo rojo rallado', 'Aderezo De Sésamo';
'Ajo', 'Cebollas de verdeo', 'Eneldo', 'Tomate', 'Limón', 'Espaguetis', 'Orégano seco', 'Concentrado de caldo de verduras', 'Queso crema', 'Queso Feta', 'Espinaca';
'Lomo de cerdo', 'Lima', 'Mayonesa', 'Piña', 'Mezcla de Especias Mexicanas', 'Jalapeño', 'Cebolla morada', 'Verduras mixtas', 'Crema agria';
